
;RHYTHM EFFECTS CHANNEL SELECTOR DATA TABLE

TABLA_DATOS_CANAL_SFX:

    defw	SELECT_CANAL_A,SELECT_CANAL_B,SELECT_CANAL_C


;BYTE 0:SFX_L
;BYTE 1:SFX_H
;BYTE 2:SFX_V
;BYTE 3:SFX_MIX

SELECT_CANAL_A:	defw	PSG_REG_SEC+0,PSG_REG_SEC+1,PSG_REG_SEC+8
    defb	10110001B

SELECT_CANAL_B:	defw	PSG_REG_SEC+2,PSG_REG_SEC+3,PSG_REG_SEC+9
    defb	10101010B

SELECT_CANAL_C:	defw	PSG_REG_SEC+4,PSG_REG_SEC+5,PSG_REG_SEC+10
    defb	10011100B


;____________________________________


INTERR:         defb     0
    ;SWITCHES 1=ON 0=OFF
    ;BIT 0=LOAD SONG ON/OFF
    ;BIT 1=PLAYER ON/OFF
    ;BIT 2=EFFECTS ON/OFF
    ;BIT 3=SFX ON/OFF
    ;BIT 4=LOOP
;CONTROL OF INTERRUPTIONS

;HOOK:           defb     0

;MUSICA **** EL ORDEN DE LAS VARIABLES ES FIJO ******



SONG:           defb     0  ;DB SONG #
TEMPO:          defb     0  ;defb TEMPO
TTEMPO:         defb     0  ;defb TEMPO COUNTER

PUNTERO_A:      defw     0  ;defw CHANNEL POINTER A
PUNTERO_B:      defw     0  ;defw CHANNEL POINTER B
PUNTERO_C:      defw     0  ;defw CHANNEL POINTER C
PUNTERO_EFECTO: defw     0  ;DW PLAYING SOUND POINTER; PLAYS EFFECTS

CANAL_A:        defw     0  ;defw DIRECTION OF START OF THE MUSIC A
CANAL_B:        defw     0  ;defw DIRECTION OF START OF THE MUSIC B
CANAL_C:        defw     0  ;defw DIRECTION OF START OF THE MUSIC C
CANAL_EFECTOS:	defb	 3  ;DB : 1:CANAL A - 2:CANAL B - OTRO:CANAL C

PUNTERO_P_A:    defw     0  ;defw CHANNEL GUIDANCE POINTER A
PUNTERO_P_B:    defw     0  ;defw CHANNEL GUIDANCE POINTER B
PUNTERO_P_C:    defw     0  ;defw CHANNEL GUIDANCE POINTER C

PUNTERO_P_A0:   defw     0  ;defw INI POINTER GUIDELINE CHANNEL A
PUNTERO_P_B0:   defw     0  ;defw INI POINTER GUIDELINE CHANNEL B
PUNTERO_P_C0:   defw     0  ;defw INI POINTER GUIDELINE CHANNEL C

PUNTERO_P_DECA:	defw	0   ;defw CHANNEL DECODER HOME POINTER A
PUNTERO_P_DECB:	defw	0   ;defw CHANNEL DECODER HOME POINTER B
PUNTERO_P_DECC:	defw	0   ;defw CHANNEL DECODER HOME POINTER C

PUNTERO_DECA:	defw	0	;defw POINTER DECODER CANAL A
PUNTERO_DECB:	defw	0	;defw POINTER DECODER CANAL B
PUNTERO_DECC:	defw	0	;defw POINTER DECODER CANAL C

REG_NOTA_A:     defb	0	;defb RECORDING THE NOTE ON THE CHANNEL A
VOL_INST_A:     defb	0	;defb RELATIVE VOLUME OF THE CHANNEL INSTRUMENT A
REG_NOTA_B:     defb	0	;defb RECORDING THE NOTE ON THE CHANNEL B
VOL_INST_B:     defb	0	;defb RELATIVE VOLUME OF THE CHANNEL INSTRUMENT B					;EMPTY
REG_NOTA_C:     defb	0	;defb RECORDING THE NOTE ON THE CHANNEL C
VOL_INST_C:     defb	0	;defb RELATIVE VOLUME OF THE CHANNEL INSTRUMENT C

PUNTERO_L_DECA:	defw	0	;defw CHANNEL DECODER LOOP START POINTER A
PUNTERO_L_DECB:	defw	0	;defw CHANNEL DECODER LOOP START POINTER B
PUNTERO_L_DECC:	defw	0	;defw CHANNEL DECODER LOOP START POINTER C

;RHYTHM EFFECTS CHANNEL - MASK ANOTHER CHANNEL

PUNTERO_P:      defw    0   ;defw CHANNEL POINTER EFFECTS
CANAL_P:        defw    0   ;defw DIRECTION OF START OF EFFECTS
PUNTERO_P_DECP:	defw	0	;defw CHANNEL DECODER HOME POINTER P
PUNTERO_DECP:	defw	0	;defw CHANNEL DECODER POINTER P
PUNTERO_L_DECP:	defw	0	;defw CHANNEL DECODER LOOP START POINTER P
;SELECT_CANAL_P	defb	INTERR+$36	;defb RHYTHM EFFECTS CHANNEL SELECTION


SFX_L:		defw	0	;defw ;BUFFER ADDRESS EFFECTS OF LOW REGISTRATION RATE
SFX_H:		defw	0	;BUFFER ADDRESS EFFECTS OF HIGH REGISTRATION RHYTHM
SFX_V:		defw	0	;defw BUFFER ADDRESS EFFECTS OF RHYTHM RECORD VOLUME
SFX_MIX:	defw	0	;defw BUFFER ADDRESS EFFECTS OF RHYTHM MIXER REGISTRATION


;SOUND EFFECTS

N_SONIDO:        defb     0      ;defb : SOUND NUMBER
PUNTERO_SONIDO:  defw     0      ;defw : POINTER OF THE SOUND THAT IS REPRODUCED



;defb (13) ; PSG RECORD BUFFERs

PSG_REG:         defs	16
PSG_REG_SEC:	 defs	16
ENVOLVENTE:	 defb	0
	;defb : SHAPE OF THE ENVELOPE
	;BIT 0	  : FREQUENCY CHANNEL ON/OFF
	;BIT 1-2  : RATIO
	;BIT 3-3  : SHAPE

ENVOLVENTE_BACK: defb	0		;defb:	BACKUP OF THE SHAPE OF THE ENVELOPE


BUFFER_CANAL_A: defs    $10;$10
BUFFER_CANAL_B: defs    $10;$10
BUFFER_CANAL_C: defs    $10;$10
BUFFER_CANAL_P: defs    $10;$10

BUFFER_DEC:     defs $10*4	;defs $20*4

; SONGS TABLE
TABLA_SONG:
	defw	BUFFER_UNCOMP

;*************************
; USER VARIABLES
; a lot of attention!!!!
; here the song is decoded you have to leave enough free space.
;*************************
BUFFER_UNCOMP:
	defs 4845
; Space for the largest MUS file

TABLA_SONG_CMP:
	defw	SONG_0;	, SONG_1

; SONGS LABELS
SONG_0:
	BINARY "zzsong.zx0"
